oriblog/blog_posts/forms.py
# Blog Posts
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class BlogPostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    text = TextAreaField('Text', validators=[DataRequired()])
    submit = SubmitField('Post')

oriblog/blog_posts/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import current_user, login_required
from oriblog import db
from oriblog.models import BlogPost
from oriblog.blog_posts.forms import BlogPostForm

blog_posts = Blueprint('blog_posts', __name__)

# CREATE
@blog_posts.route('/create', methods=['GET', 'POST'])
@login_required
def create_post():
    form = BlogPostForm()

    if form.validate_on_submit():

        blog_post = BlogPost(title=form.title.data,
                             text=form.text.data,
                             user_id=current_user.id
                             )
        db.session.add(blog_post)
        db.session.commit()
        flash("Post Created")
        return redirect(url_for('core.index'))

    return render_template('create_post.html', form=form)

# READ
@blog_posts.route('/<int:blog_post_id>')
def blog_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    return render_template('blog_post.html', title=blog_post.title,
                           date=blog_post.date, post=blog_post
                           )

# UPDATE
@blog_posts.route("/<int:blog_post_id>/update", methods=['GET', 'POST'])
@login_required
def update(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    if blog_post.author != current_user:
        abort(403)

    form = BlogPostForm()
    if form.validate_on_submit():
        blog_post.title = form.title.data
        blog_post.text = form.text.data
        db.session.commit()
        flash('Post Updated')
        return redirect(url_for('blog_posts.blog_post', blog_post_id=blog_post.id))
    elif request.method == 'GET':
        form.title.data = blog_post.title
        form.text.data = blog_post.text
    return render_template('create_post.html', title='Update',
                           form=form)

# DELETE
@blog_posts.route("/<int:blog_post_id>/delete", methods=['POST'])
@login_required
def delete_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    if blog_post.author != current_user:
        abort(403)
    db.session.delete(blog_post)
    db.session.commit()
    flash('Post has been deleted.')
    return redirect(url_for('core.index'))

oriblog/core/views.py
from oriblog.models import BlogPost
from flask import render_template, request, Blueprint

core = Blueprint('core', __name__)


@core.route('/')
def index():
    page = request.args.get('page', 1, type=int)
    blog_posts = BlogPost.query.order_by(
        BlogPost.date.desc()).paginate(page=page, per_page=5)
    return render_template('index.html', blog_posts=blog_posts)


@core.route('/info')
def info():
    return render_template('info.html')

oriblog/users/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from oriblog import db
from werkzeug.security import generate_password_hash,check_password_hash
from oriblog.models import User, BlogPost
from oriblog.users.forms import RegistrationForm, LoginForm, UpdateUserForm
from oriblog.users.photo_handler import add_profile_pic


users = Blueprint('users', __name__)

@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,
                    password=form.password.data)

        db.session.add(user)
        db.session.commit()
        flash('You are now registered.')
        return redirect(url_for('users.login'))
    return render_template('register.html', form=form)

@users.route('/login', methods=['GET', 'POST'])
def login():

    form = LoginForm()
    if form.validate_on_submit():
        # Get user from table
        user = User.query.filter_by(email=form.email.data).first()

        # Validate user and pswd
        if user.check_password(form.password.data) and user is not None:
            #Log in the user

            login_user(user)
            flash('You are now logged in.')

            # If user was trying to log in to a walled page, take them there after login
            next = request.args.get('next')

            # If user exists, go to Welcome page
            if next == None or not next[0]=='/':
                next = url_for('blog_posts.create_post')

            return redirect(next)
    return render_template('login.html', form=form)

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('core.index'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():

    form = UpdateUserForm()

    if form.validate_on_submit():
        print(form)
        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data,username)
            current_user.profile_image = pic

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Account Updated')
        return redirect(url_for('users.account'))

    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_image = url_for('static', filename='imgs/' + current_user.profile_image)
    return render_template('account.html', profile_image=profile_image, form=form)


@users.route("/<username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    blog_posts = BlogPost.query.filter_by(author=user).order_by(BlogPost.date.desc()).paginate(page=page, per_page=5)
    return render_template('user_blog_posts.html', blog_posts=blog_posts, user=user)

oriblog/templates/account.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <div align='center'>
    <h1 >Welcome {{ current_user.username }}!</h1>
    <img class="user-img" align='center' src="{{ url_for('static', filename='imgs/' + current_user.profile_image) }}">
    <p>{{ current_user.email }}</p>
  </div>
</div>
<div class="container">
  <form  method="POST" action = "" enctype="multipart/form-data">
    {{ form.hidden_tag() }}
    <div class="form-group">
      {{ form.username.label(class="form-group") }}
      {{ form.username(class='form-control')  }}
    </div
    <div class="form-group">
      {{ form.email.label(class="form-group") }}
      {{ form.email(class='form-control')  }}
    </div>
    <br />
    <div class="form-group ml-3">
      {{ form.picture.label(class="form-group") }}
      {{ form.picture(class="form-control-file") }}
    </div>
    <br />
    <div class="form-group ml-3">
        {{ form.submit(class="btn btn-primary") }}
    </div>
  </form>
</div>
{% endblock %}

oriblog/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/' + 'style.css') }}">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <link
    href="https://fonts.googleapis.com/css?family=Montserrat&display=swap"
    rel="stylesheet"
  />
  <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css"
  />
    <title></title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <ul class="nav">
    <li class="nav-item">
      <a class="nav-link" href="{{ url_for('core.index') }}">Home</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{{ url_for('core.info') }}">About</a>
    </li>
      {% if current_user.is_authenticated %}
      <li class="nav-link"><a href="{{ url_for('users.logout') }}">Log Out</a></li>
      <li class="nav-link"><a href="{{ url_for('users.account') }}">Account</a></li>
      <li class="nav-link"><a href="{{ url_for('blog_posts.create_post') }}">Create Post</a></li>
      {% else %}
      <li class="nav-link"><a href="{{ url_for('users.login') }}">Log In</a></li>
      <li class="nav-link"><a href="{{ url_for('users.register') }}">Register</a></li>
      {% endif %}
  </ul>
</nav>
  <div class="container">
    {% block content %}
  
    {% endblock %}
  </div>

  
    </body>
</html>

oriblog/templates/blog_post.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <h1>{{ post.title }}</h1>
  <p>Author: {{post.author.username}}</p>
  <p>Created: {{post.date.strftime('%B %d, %Y')}}</p>
  <p>{{post.text}}</p>

  {% if post.author == current_user %}
  <div>
    <a class="btn btn-info" href="{{url_for('blog_posts.update',blog_post_id=post.id)}}">Update</a>
    <button
      type="button"
      class="btn btn-danger"
      data-toggle="modal"
      data-target="#delete_modal"
    >
      Delete
    </button>
  </div>
  {% endif %}
</div>
<!-- PopUp Modal -->
<div id="delete_modal" class="modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Delete Post</h5>
        <button
          type="button"
          class="close"
          data-dismiss="modal"
          aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to delete?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">
          Cancel
        </button>
          <form
          action="{{ url_for('blog_posts.delete_post', blog_post_id=post.id) }}"
          method="POST">
          <input class="btn btn-danger" type="submit" value="Delete" />
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

oriblog/templates/create_post.html
{% extends "base.html" %}
{% block content %}
<br>
<div class="jumbotron">
  <div align='center'>
    <h1 class="animated fadeIn">Welcome {{ current_user.username }}!</h1>
    <img class="user-img animated fadeIn delay-1s" align='center' src="{{ url_for('static', filename='imgs/' + current_user.profile_image) }}">
    <p class="user-img animated fadeInUp">{{ current_user.email }}</p>
  </div>
</div>
<div class="container">
  <form class="form-group" method="POST">
     {{ form.hidden_tag() }}
    <h2 class="animated fadeInLeft delay-1s">Create and publish your post.</h2>
    <p class="animated fadeInLeft delay-1s">All user posts are displayed on the home page.</p>
     <div class="form-group animated fadeInLeft delay-1s">
     {{ form.title.label(class="form-control-label") }}
     {{ form.title(class="form-control form-control-lg ") }}
     </div>
     <div class="form-group animated fadeInLeft delay-1s">
     {{ form.text.label(class="form-control-label") }}
     {{ form.text(class="form-control form-control-lg") }}
     </div>
     <div class="form-group animated fadeIn delay-2s">
         {{ form.submit(class="btn btn-outline-info") }}
     </div>
  </form>
</div>
{% endblock %}

oriblog/templates/index.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <div class="container header-container">
    <div class="row">
      <div class="col-sm-8 header-text-main">
        <h1 class="animated fadeInLeft">Welcome to OriBlog</h1>
      </div>
      <div class="col-sm-4 header-img">
        <img class="animated fadeInRight" src="{{ url_for('static', filename='imgs/' + 'blue.png') }}" alt="blue origami butterfly">
      </div>
    </div>
  </div>
</div>
<div class="container">
    {% for post in blog_posts.items %}
    <div class="card animated fadeIn delay-1s" >
      <div class="card-body">
        <h2><a class="card-title" href="  {{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}">{{ post.title }}</a></h2>
        <a href="{{ url_for('users.user_posts', username=post.author.username) }}" class="author">Author: {{ post.author.username }}</a>
        <p>Created on: {{ post.date.strftime('%Y-%m-%d') }}</p>
        <p class="card-text">{{ post.text[:100] }}...</p>
        <a href="{{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}" class="btn btn-primary">Read More</a>
      </div>
    </div>
   {% endfor %}
   <nav aria-label="Page navigation example">
     <ul class="pagination justify-content-center">
       {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
          {% if blog_posts.page == page_num %}
          <li class="page-item disabled">
            <a class="page-link" href="{{ url_for('core.index', page=page_num) }}">{{ page_num }}</a></li>
          </li>
          {% else %}
            <li class="page-item"><a class="page-link" href="{{ url_for('core.index', page=page_num) }}">{{ page_num }}</a></li>
          {% endif %}
      {% endfor %}
    </nav>
{% endblock %}

oriblog/templates/info.html
{% extends "base.html" %} {% block content %}
<div class="jumbotron">
  <div class="container header-container">
    <div class="row">
      <div class="col-sm-6 header-text">
        <h1 class="animated fadeInDown">About Us</h1>
        <p class="animated fadeIn delay-1s">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero magni magnam
          repudiandae labore praesentium iusto maiores earum. Voluptatum distinctio
          harum tempore nihil nemo dolores hic consectetur. Vitae aliquid explicabo
          possimus, cupiditate iusto minima illum laborum quidem, odio vel nobis
          perspiciatis suscipit praesentium maxime voluptatum? Ratione incidunt eum
          corrupti molestiae fuga!
        </p>
      </div>
      <div class="col-sm-6 header-img">
        <img class="animated fadeIn delay-1s" src="{{ url_for('static', filename='imgs/' + 'penguin.png') }}" alt="purple origami penguin">
      </div>
    </div>
  </div>
</div>
{% endblock %}

oriblog/templates/login.html
{% extends "base.html" %} {% block content%}
<div class="jumbotron">
  <div class="container header-container">
    <div class="row">
      <div class="col-sm-6 header-text">
        <h1 class="animated fadeIn">Sign In</h1>
        <form method="POST">
          <div class="container" align="left">
          {{form.hidden_tag()}}
          <!--  -->
          {{form.email.label(class="animated fadeIn")}}
          <br />
          {{form.email(class='form-group animated fadeIn')}} 
          <br />
          {{form.password.label(class="animated fadeIn")}}
          <br />
          {{form.password(class='form-group animated fadeIn')}} <br />
          <br />
          {{form.submit(class='btn btn-info animated fadeIn delay-1s')}}
        </div>
        </form>
      </div>
      <div class="col-sm-6 header-img">
        <img class="animated fadeIn delay-1s" src="{{ url_for('static', filename='imgs/' + 'fox.png') }}" alt="green origami fox">
      </div>
    </div>
  </div>
</div>
{% endblock %}

oriblog/templates/register.html
{% extends "base.html" %} {% block content%}
<div class="jumbotron">
  <div class="container header-container">
    <div class="row">
      <div class="col-sm-6 header-text">
        <h1 class="title animated fadeInDown">Sign up today!</h1>
        <p class="title animated fadeIn delay-1s">Receive full access to post your articles.</p>
        <br />
        <form action="" method="POST">
          <div class="container" align="left">
          {{form.hidden_tag()}}
          <!--  -->
          {{form.email.label(class='form-group animated fadeInLeft')}}
          <br />
          {{form.email(class='form-group animated fadeInLeft')}}
          <br />
          {{form.username.label(class='form-group animated fadeInLeft')}}
          <br />
          {{form.username(class='form-group animated fadeInLeft')}}
          <br />
          {{form.password.label(class='form-group animated fadeInLeft')}}
          <br />
          {{form.password(class='form-group animated fadeInLeft')}}
          <br />
          {{form.password_confirm.label(class='form-group animated fadeInLeft')}}
          <br />
          {{form.password_confirm(class='form-group animated fadeInLeft')}}
          <br />
          <br />
          {{form.submit(class='btn btn-primary animated fadeIn delay-1s')}}
          </div>
        </form>
      </div>
      <div class="col-sm-6 header-img">
        <img class="animated fadeIn delay-1s" src="{{ url_for('static', filename='imgs/' + 'heart.png') }}" alt="blue origami heart">
      </div>
    </div>
  </div>
</div>
{% endblock %}

oriblog/templates/user_blog_posts.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <div class="jumbotron">
    <div align='center'>
      <h1 >Hello {{user.username}}</h1>
      <img align='center' src="{{ url_for('static', filename='imgs/' + user.profile_image) }}">
    </div>
  </div>
{% for post in blog_posts.items %}
          <h2><a href="{{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}">{{ post.title }}</a></h2>
          Created by: <a href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
          <p class="text-muted">Created on: {{ post.date.strftime('%Y-%m-%d') }}</p>
          <br>
            <p>{{post.text}}</p>
          <br>
{% endfor %}
</div>
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if blog_posts.page == page_num %}
              <li class="page-item disabled">
                <a class="page-link" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a></li>
              </li>
            {% else %}
              <li class="page-item"><a class="page-link" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a></li>
            {% endif %}
    {% endfor %}
</nav>
{% endblock content %}